# Generated by Django 5.0.2 on 2026-03-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil o identificación del empleado', null=True, upload_to='empleados/fotos/'),
        ),
        migrations.AlterField(
            model_name='historialpuesto',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puestos', to='empleados.empleado'),
        ),
    ]
