# Generated by Django 5.0.2 on 2026-03-26 16:28

import apps.empleados.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_foto_perfil_alter_historialpuesto_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil o identificación del empleado', null=True, upload_to=apps.empleados.utils.generar_nombre_foto_empleado),
        ),
    ]
